package io.github.bi.domain;

/*-
 * Money Market Bi - BI Microservice for Money Market Bi deals is part of the Granular Bi System
 * Copyright © 2025 Edwin Njeru (mailnjeru@gmail.com)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

import static org.assertj.core.api.Assertions.assertThat;

public class FiscalYearAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFiscalYearAllPropertiesEquals(FiscalYear expected, FiscalYear actual) {
        assertFiscalYearAutoGeneratedPropertiesEquals(expected, actual);
        assertFiscalYearAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFiscalYearAllUpdatablePropertiesEquals(FiscalYear expected, FiscalYear actual) {
        assertFiscalYearUpdatableFieldsEquals(expected, actual);
        assertFiscalYearUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFiscalYearAutoGeneratedPropertiesEquals(FiscalYear expected, FiscalYear actual) {
        assertThat(actual)
            .as("Verify FiscalYear auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFiscalYearUpdatableFieldsEquals(FiscalYear expected, FiscalYear actual) {
        assertThat(actual)
            .as("Verify FiscalYear relevant properties")
            .satisfies(a -> assertThat(a.getFiscalYearCode()).as("check fiscalYearCode").isEqualTo(expected.getFiscalYearCode()))
            .satisfies(a -> assertThat(a.getStartDate()).as("check startDate").isEqualTo(expected.getStartDate()))
            .satisfies(a -> assertThat(a.getEndDate()).as("check endDate").isEqualTo(expected.getEndDate()))
            .satisfies(a -> assertThat(a.getFiscalYearStatus()).as("check fiscalYearStatus").isEqualTo(expected.getFiscalYearStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFiscalYearUpdatableRelationshipsEquals(FiscalYear expected, FiscalYear actual) {
        assertThat(actual)
            .as("Verify FiscalYear relationships")
            .satisfies(a -> assertThat(a.getPlaceholders()).as("check placeholders").isEqualTo(expected.getPlaceholders()));
    }
}
