package io.github.bi.domain;

/*-
 * Money Market Bi - BI Microservice for Money Market Bi deals is part of the Granular Bi System
 * Copyright © 2025 Edwin Njeru (mailnjeru@gmail.com)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

import static org.assertj.core.api.Assertions.assertThat;

public class MoneyMarketUploadNotificationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMoneyMarketUploadNotificationAllPropertiesEquals(
        MoneyMarketUploadNotification expected,
        MoneyMarketUploadNotification actual
    ) {
        assertMoneyMarketUploadNotificationAutoGeneratedPropertiesEquals(expected, actual);
        assertMoneyMarketUploadNotificationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMoneyMarketUploadNotificationAllUpdatablePropertiesEquals(
        MoneyMarketUploadNotification expected,
        MoneyMarketUploadNotification actual
    ) {
        assertMoneyMarketUploadNotificationUpdatableFieldsEquals(expected, actual);
        assertMoneyMarketUploadNotificationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMoneyMarketUploadNotificationAutoGeneratedPropertiesEquals(
        MoneyMarketUploadNotification expected,
        MoneyMarketUploadNotification actual
    ) {
        assertThat(actual)
            .as("Verify MoneyMarketUploadNotification auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMoneyMarketUploadNotificationUpdatableFieldsEquals(
        MoneyMarketUploadNotification expected,
        MoneyMarketUploadNotification actual
    ) {
        assertThat(actual)
            .as("Verify MoneyMarketUploadNotification relevant properties")
            .satisfies(a -> assertThat(a.getErrorMessage()).as("check errorMessage").isEqualTo(expected.getErrorMessage()))
            .satisfies(a -> assertThat(a.getRowNumber()).as("check rowNumber").isEqualTo(expected.getRowNumber()))
            .satisfies(a -> assertThat(a.getReferenceNumber()).as("check referenceNumber").isEqualTo(expected.getReferenceNumber()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMoneyMarketUploadNotificationUpdatableRelationshipsEquals(
        MoneyMarketUploadNotification expected,
        MoneyMarketUploadNotification actual
    ) {
        assertThat(actual)
            .as("Verify MoneyMarketUploadNotification relationships")
            .satisfies(a -> assertThat(a.getMoneyMarketList()).as("check moneyMarketList").isEqualTo(expected.getMoneyMarketList()))
            .satisfies(a -> assertThat(a.getReportBatch()).as("check reportBatch").isEqualTo(expected.getReportBatch()))
            .satisfies(a -> assertThat(a.getPlaceholders()).as("check placeholders").isEqualTo(expected.getPlaceholders()));
    }
}
